version: '3.9'

services:
  api:
    container_name: ph-nest-api

    build:
      context: .

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      NODE_ENV: development

    command: npm run start:dev

  redis:
    image: redis:7-alpine
    container_name: ph-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

volumes:
  redis_data: